### ISSUE TITLE
Post: Developer Workstation Automation

### ISSUE THREAD

**Issue by scottmuc** [scottmuc/scottmuc.github.com#7]
## Source

https://github.com/scottmuc/scottmuc.github.com/blob/source/source/_posts/2016-10-11-osx-workstation-setup-automation.markdown
## Notes
- ~~Hierarchy of dependencies (should Vagrant be in workstation or in project?)~~ (too much info for this blog post)
- ~~What should be vendored~~ (addressed in duplication section, but needs to be moved to the appendix)
- ~~but but but but... containers!~~ (ignore for now, there's enough to talk about in this post)
- ~~been a thing since '99 (http://joeyh.name/svnhome/)~~ (will be added to the appendix
## Tasks:
- [x] Objective statement
- [x] How to reinstall El Capitan
- [x] SSH key managment
- [x] What are the alternatives
- [x] How does my automation work
- [x] Why start with `$HOME`
- [x] Why still use sprout-wrap
- [x] Document rational around vim setup (pathogen + submodules vs the rest)
- [x] Create a rough manifest describing the major pieces of the automation.
- [x] Machine level and workstation level duplication
- [x] Move other tools into an "appendix"
- [x] Focus on personal workstation, and leave out workplace specific (may require removal of duplication tangent, or moving it to the "appendix")
- [x] Add details around secrets management to use a password manager as an alternative to USB
- [x] Add a disclaimer and write about how I treat my system as a stateless environment
- [x] Typo scan
- [x] Restructure to go over my process (with timing info) and break rationale into "appendix" segments.
- [x] Move some rationale arguments into the `osx-homedir` repository?
- [x] Add http://joeyh.name/svnhome/ to "appendix"
